<!-- ===============================================-->
<!--    Favicons-->
<!-- ===============================================-->
<link href="/public/images/favicons/favicon.ico" rel="icon">
<?PHP
/*
<link rel="apple-touch-icon" sizes="180x180" href="/public/assets/img/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/public/assets/img/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/public/assets/img/favicons/favicon-16x16.png">
<link rel="shortcut icon" type="image/x-icon" href="/public/assets/img/favicons/favicon.ico">
<link rel="manifest" href="/public/assets/img/favicons/manifest.json">
<meta name="msapplication-TileImage" content="/public/assets/img/favicons/mstile-150x150.png">
*/