<div class="mb-3">
    <label for="security-icon" class="form-label">Select Security Credential Icon</label>
    <select class="form-select" name="security-icon" id="security-icon">
        <option value="bi-person"><i class="bi bi-person"></i> Username</option>
        <option value="bi-lock"><i class="bi bi-lock"></i> Password</option>
        <option value="bi-key"><i class="bi bi-key"></i> SSH Key</option>
        <option value="bi-keypad"><i class="bi bi-keypad"></i> API Key</option>
        <option value="bi-award"><i class="bi bi-award"></i> Certificate</option>
        <option value="bi-fingerprint"><i class="bi bi-fingerprint"></i> Fingerprint Authentication</option>
        <option value="bi-eye"><i class="bi bi-eye"></i> Biometric Authentication</option>
        <option value="bi-shield-check"><i class="bi bi-shield-check"></i> Multi-factor Authentication</option>
        <option value="bi-shield"><i class="bi bi-shield"></i> Security Token</option>
        <option value="bi-globe"><i class="bi bi-globe"></i> VPN</option>
    </select>
</div>