<?PHP

$outputcontent .= '
<!-- File Fields -->
<div class="mb-3">
<label for="edit-file-title" class="form-label">File Title</label>
<input type="text" class="form-control" id="edit-file-title" name="file_title" placeholder="Enter file title">
</div>

<div class="mb-3">
<label for="edit-file-upload" class="form-label">Upload File</label>
<input type="file" class="form-control" id="edit-file-upload" name="file_upload">
</div>
<input type="hidden" id="hiddenFieldId" name="passwordstrength" value="100">
';
