<?PHP

$link = [
  'home' => [
    'title' => 'Home',
    'url' => '/',
    'icon' => 'bi-house',
    'description' => 'The home page of birthday.gold'
  ],
  'myaccount' => [
    'title' => 'My Account',
    'url' => '/myaccount',
    'icon' => 'bi-person',
    'description' => 'Your account page'
  ],
  'enrollment' => [
    'title' => 'Enrollment',
    'url' => '/myaccount/enrollment',
    'icon' => 'bi-file-earmark-person',
    'description' => 'Enroll in birthday.gold'
  ],
  'memberenrollmentselector' => [
    'title' => 'Enrollment',
    'url' => '/myaccount/businessselect',
    'icon' => 'bi-file-earmark-person',
    'description' => 'Enroll in birthday.gold'
  ],
  'brands' => [
    'title' => 'Brands',
    'url' => '/brands',
    'icon' => '',
    'description' => ''
  ],
  // Add more links as needed
];